### ISSUE TITLE
The fixed Restaurant part

### ISSUE THREAD

**Issue by LiheYoung** [blackjack2015/IRS#10]
Hi, thank you for contributing such an amazing dataset! 

I noticed that you updated the Restaurant part. After extracting from these updated parts, there are only 2,983 paired samples, rather than 22,058 pairs reported in the README. I checked the extracted files from the fixed zips, finding that many RGB files are missed with only disparity map and normal map remained. I wonder that whether this is by intention. Thank you.

**Comment by LiheYoung** [comment]
I found the download links have been updated. Thanks a lot.

**Comment by CJCHEN1230** [comment]
@LiheYoung  Hi, the onedrive link is dead. Could you provide me the new link? Thanks a lot.
