### ISSUE TITLE
Google drive link doesn't work

### ISSUE THREAD

**Issue by dorp92** [blackjack2015/IRS#12]
Hi, Looks like an amazing dataset but I can't download it.
Any chance for anther download method beside baidu for the people out of china?
Many thanks

**Comment by WeijianZhang123** [comment]
+1

**Comment by JuWanMaeng** [comment]
+100

**Comment by blackjack2015** [comment]
Hi Alls,
Please refer to the update OneDrive link: https://1drv.ms/f/s!AmN7U9URpGVGem0coY8PJMHYg0g?e=ZAkMyz

Hope you enjoy it.

Bests

**Comment by Guptajakala** [comment]
@blackjack2015 on onedrive, when I click download, the webpage does not response. Do you still have the google drive link?

**Comment by Guptajakala** [comment]
the files are probably too big for the cloud storages to process. Could you subdivide the files into more zip files? @blackjack2015

**Comment by dorp92** [comment]
> Hi Alls, Please refer to the update OneDrive link: https://1drv.ms/f/s!AmN7U9URpGVGem0coY8PJMHYg0g?e=ZAkMyz
> 
> Hope you enjoy it.
> 
> Bests

Many Thanks!
