### ISSUE TITLE
Broken Dataset Links

### ISSUE THREAD

**Issue by tarekmuallim** [blackjack2015/IRS#13]
Hello @blackjack2015 ,
I wanted to let you know that the links for the datasets in this repository are broken.
I've tried accessing them but haven't been successful.
Could you please check and update the links?
Thank you!

**Comment by blackjack2015** [comment]
> Hello @blackjack2015 , I wanted to let you know that the links for the datasets in this repository are broken. I've tried accessing them but haven't been successful. Could you please check and update the links? Thank you!

Hi, 
Please refer to the update OneDrive link: https://1drv.ms/f/s!AmN7U9URpGVGem0coY8PJMHYg0g?e=ZAkMyz

Hope you enjoy it.

Bests

**Comment by tarekmuallim** [comment]
Hi @blackjack2015 ,

Thank you for the update! I'll check it out soon.

Best regards.
