### ISSUE TITLE
what is the IRS_small?

### ISSUE THREAD

**Issue by Guptajakala** [blackjack2015/IRS#14]
![image](https://github.com/blackjack2015/IRS/assets/40518028/7e491bdc-066b-485c-98ea-99dfbed44bb2)

Hi, thanks for the great work! What is the IRS_small file? Is it just a subset duplication from the rest of the tar files?

**Comment by blackjack2015** [comment]
> ![image](https://private-user-images.githubusercontent.com/40518028/335842461-7e491bdc-066b-485c-98ea-99dfbed44bb2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczMTE1NzgsIm5iZiI6MTcxNzMxMTI3OCwicGF0aCI6Ii80MDUxODAyOC8zMzU4NDI0NjEtN2U0OTFiZGMtMDY2Yi00ODVjLTk4ZWEtOTlkZmJlZDQ0YmIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAyVDA2NTQzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4NDU2NDk5ZDQzOGY5MTRiODBmZDM2Nzg5YTcxZmY4ZGRiYmM5ZTMzMmRhZmQ3ZjRlNzc0Njk3MDBmMGE2NjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QRnOFXMbA2RBwndyzqnO_6scQcvSeEZYU_jqlohsIPY)
> 
> Hi, thanks for the great work! What is the IRS_small file? Is it just a subset duplication from the rest of the tar files?

Hi,

The samples in IRS_small are just evenly sampled from the complete IRS for fast access and model validation, since downloading the complete IRS may take long time (totally near 600 GB).

Best,
Qiang Wang
