### ISSUE TITLE
The download link shows error

### ISSUE THREAD

**Issue by ckwang** [blackjack2015/IRS#17]
Hi, the download link is currently not working. It's showing this error.
<img width="346" alt="Screenshot 2024-07-17 at 11 05 11 AM" src="https://github.com/user-attachments/assets/b3fa0ff2-b0ba-48c9-9baf-cfd85e939724">

**Comment by blackjack2015** [comment]
> Hi, the download link is currently not working. It's showing this error. <img alt="Screenshot 2024-07-17 at 11 05 11 AM" width="346" src="https://private-user-images.githubusercontent.com/521431/349624983-b3fa0ff2-b0ba-48c9-9baf-cfd85e939724.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyODMwNjksIm5iZiI6MTcyMTI4Mjc2OSwicGF0aCI6Ii81MjE0MzEvMzQ5NjI0OTgzLWIzZmEwZmYyLWIwYmEtNDhjOS05YmFmLWNmZDg1ZTkzOTcyNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxOFQwNjA2MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jM2MxMjE1OGJhMGM4MjYyNjgxNjVlM2ExODc2YTM1ZWMwYTRhOWE1N2U1MmU1Y2FjZmU2ZWFmOThiMmMyOTQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.noN9-fVdddLxeHKX8BI8RecSf9GkH69EiFriLSn5fAQ">

I have tried it and it should work now. It seems that OneDrive is banned in China Mainland and you may try a network accelerator (VPN).
