### ISSUE TITLE
unzip error from office-1, office-2, and home-2

### ISSUE THREAD

**Issue by ZYX-MLer** [blackjack2015/IRS#19]
Hello, I have tried downloading and extracting office-1, office-2, and home-2 multiple times, but I have never been able to successfully extract them completely. Has anyone else encountered the same issue?

**Comment by Qjizhi** [comment]
gzip: stdin: invalid compressed data--format violated
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now

**Comment by blackjack2015** [comment]
Yes. I have confirmed this issue and currently re-zip these three files. Hopefully release them this month. OneDrive is somehow not well working in our network.

**Comment by blackjack2015** [comment]
I have updated all the zips and now they should work fine. Thanks.

**Comment by Qjizhi** [comment]
> I have updated all the zips and now they should work fine. Thanks.

Thanks!

**Comment by ArenaGrenade** [comment]
@blackjack2015 I am facing the exact same issue with Restaurant.tar.gz which I download from onedrive on 29th Jan.
